---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    cert-manager.io/cluster-issuer: dns-clusterissuer
    gethomepage.dev/description: Jenkins build server
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: jenkins.png
    gethomepage.dev/name: Jenkins    
spec:
  rules:
    - host: jenkins.thejimnicholson.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port: 
                  number: 8080
  tls:
    - hosts:
      - jenkins.thejimnicholson.com
      secretName: jenkins-thejimnicholson-com